
apiVersion: apps/v1
kind: Deployment # type of resource
metadata:
  name: students-client
  labels:
    app: students-client

spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: students-client
  template:
    metadata:
      labels:
        app: students-client
    spec:
      containers:
        - name: students-client
          image: {{.Values.image.clientname}}
          imagePullPolicy: Always
          resources:
          ports:
            - containerPort: {{.Values.http.frontendport}}
      restartPolicy: Always