apiVersion: apps/v1
kind: Deployment
metadata:
  name: students-server
  labels:
    app: students-server

spec:
  replicas: 1
  selector:
    matchLabels:
      app: students-server
  template:
    metadata:
      labels:
        app: students-server
      annotations:
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: students-server
          image: ramikammoun2023/server
          imagePullPolicy: Always

          env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: port

          ports:
            - containerPort: 5000
