apiVersion: apps/v1
kind: Deployment
metadata:
  name: students-server
  labels:
    app: {{ toYaml .Values.labels | nindent 4 }}

spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: students-server
  template:
    metadata:
      labels:
        app: students-server
        admission.datadoghq.com/enabled: "true"
      annotations:
        prometheus.io/port: "5000"
        prometheus.io/path: "/api/metrics"
        prometheus.io/scrape: "true"
        admission.datadoghq.com/nodejs-lib.version: v3.11.0
    spec:
      containers:
        - name: students-server
          image: {{.Values.image.servername}}
          imagePullPolicy: Always

          env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: port
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_TRACE_STARTUP_LOGS
            value: "true"

          ports:
            - containerPort: {{.Values.http.backendport}}
